data:
    image: inetprocess/data
    #build: https://github.com/inetprocess/docker-data
    volumes:
        - ./home/www-data:/home/www-data
        - ./www:/var/www

apache:
    image: inetprocess/apache:${DOCKER_APACHE_VERSION}
    mem_limit: ${DOCKER_APACHE_RAM}
    hostname: apache-ctn
    environment:
        PHP_GID: ${DOCKER_GID}
    volumes_from: [data]
    volumes:
        - ./logs/apache:/var/log/apache2
    links: [php]

php:
    #image: inetprocess/php:${DOCKER_PHP_VERSION}
    image: inet_php_test
    hostname: php-ctn
    mem_limit: ${DOCKER_PHP_RAM}
    environment:
        FPM_UID: ${DOCKER_UID}
        FPM_GID: ${DOCKER_GID}
    volumes_from: [data]
    volumes:
        - ./logs/php:/var/log/php
        - ./conf/php-fpm-override:/etc/php5/fpm/user-conf.d
        - ./conf/php-fpm-override:/etc/php/7.0/fpm/user-conf.d
