---

environment: dev

services:
  portainer:
    enabled: false
    version: latest
    ram: 512M
    service_name: Portainer (Docker Webadmin)
    service_url: http://{}

aliases: {}

proxy:
  enabled: true
  domain: localhost
  http_port: 80
  https_port: 443

project_name: ''

subnet: ''

uid:
gid:
